src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['namespace' => 'App\packages\report\src\controllers', /*'prefix' => 'report',*/ 'middleware' => ['web']], function() {

/*-- Report Settings --*/

Route::resource('report_setting', 'ReportSettingController');
Route::get('report/edit', 'ReportSettingController@show');
Route::post('editAttribute', 'ReportSettingController@editAttributeField');
Route::post('report_setting/update', 'ReportSettingController@updateReportAttibutr');

Route::post('report/update', 'ReportSettingController@updateReportAttibutr');
Route::get('generate_form', 'FormsController@index');
Route::post('generic_save', 'FormsController@genericSave');

/*------------ Export Excel --------------*/

Route::get('export_to_excel', 'ExportController@export');

});

src/controllers/ReportSettingController.php
<?php

namespace App\packages\report\src\Controllers;

use App\common\Common;
use App\Exports\Export;
use App\packages\report\src\models\MasterModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use phpDocumentor\Reflection\Types\Array_;
use App\Http\Controllers\Controller;

class ReportSettingController extends Controller
{

    public function index(Request $request)
    {
       // dd($request);
        $requestData        = $request->all();
        $sessionData        = $request->session()->get('user_info');
        $masterModel        = new MasterModel();

        try {
            $addEditFormKey = 'report';

            $settings = [
                'action_edit_button'        => '1',
                'action_view_button'        => '1',
                'action_accordion_button'   => '0',
                'accordion_url'             => '',
                'add_button'                => '1',
                'pagination'                => '1',
                'filter_button'             => '0',
                'group_button'              => '1',
                'export_button'             => '1',
                'import_button'             => '0',
                'search'                    => '1',
                'list_title'                => 'Report Setting',
                'action_header'             => '1',
                'multiSaveKey'              => '',
            ];
            $headers = [
                'id'                        => 'Sr. No',
                'report_name'               => 'Report Name',
                'route_name'                => 'Route'
            ];

            $query = DB::table('report');

            if(isset($requestData['basics']) && !empty($requestData['basics'])) {
                $query->where(function ($query) use ($requestData) {
                    $query->where('report_name', 'LIKE', '%' . $requestData['basics'].'%');
                });
            }

            if(isset($requestData['filter_column_name']) && isset($requestData['sorting_method']) && !empty($requestData['filter_column_name']) && !empty($requestData['sorting_method'])){
                $query      = $query->orderBy($requestData['filter_column_name'], $requestData['sorting_method']);
            } else {
                $query      = $query->orderBy('id', 'DESC');
            }

            $export     = new Export();
            $sql_query  = $export->eloquentSqlWithBindings($query);
            $export->setExcelParameters($sql_query, $headers, $settings['list_title']);

            $paginationData = $query->paginate(10);
            $listingData = json_decode(json_encode($paginationData), true);

        }catch(\Illuminate\Database\QueryException $ex){
            //  $common     = new Common();
            //  $common->error_logging($ex, 'index', 'ReportSettingController.php');
            //  return view('errors.oh!');
            dd($ex->getMessage());
            dd($ex->getLine());
        }

        $filterFormData = '';
        $filterFields = '';

        return view('report::layouts.listing-container',compact('headers','listingData', 'paginationData', 'settings', 'addEditFormKey', 'filterFormData', 'filterFields'));
    }

    /*
     @ Show Form Field listing view.
     */
    public function show(Request $request){
        $requestData = $request->all();
        try {
            $report_id              = $requestData['id'];
            $reportData             = DB::table('report')->where('id', $report_id)->first();
            $reportAttributeData    = DB::table('report_attribute')->where('report_id', $report_id)->orderBy('id', 'DESC')->paginate(10);

        }catch(\Illuminate\Database\QueryException $ex){
            // $common     = new Common();
            // $common->error_logging($ex, 'show', 'FormSettingController.php');
            // return view('errors.oh!');
            dd($ex->getMessage());
            dd($ex->getLine());
        }
        return view('report::super_admin.Master.report_setting.reportSetting', compact('reportData','report_id', 'reportAttributeData'));
    }

    /*
    @ Store form field.
    */
    public function store(Request $request)
    {
        $requestData = $request->all();
        $masterModel = new MasterModel();

        try {
            $insertField['report_id']           = $requestData['report_id'];
            $insertField['attribute_name']      = $requestData['attribute_name'];

            $masterModel->insertData($insertField,'report_attribute');

        }catch(\Illuminate\Database\QueryException $ex){
            // $common     = new Common();
            // $common->error_logging($ex, 'store', 'ReportSettingController.php');
            // return view('errors.oh!');
            dd($ex->getMessage());
            dd($ex->getLine());
        }
        return redirect('report_setting/edit?id='.$requestData['report_id'])->with('success','Field Created successfully');
    }

    /*
     @ Edit Form Field.
     */
    public function editAttributeField(Request $request)
    {
        $requestData = $request->all();
        $masterModel = new MasterModel();

        try {
            $where['id'] = $requestData['attribute_id'];
            $fieldDetails = $masterModel->getMasterRow('report_attribute', $where);
            return json_encode($fieldDetails);

        }catch(\Illuminate\Database\QueryException $ex){
            // $common     = new Common();
            // $common->error_logging($ex, 'Edit', 'ReportSettingController.php');
            // return view('errors.oh!');
            dd($ex->getMessage());
            dd($ex->getLine());
        }
    }

    /*
    @ Store form field.
    */
    public function updateReportAttibutr(Request $request)
    {
        $requestData = $request->all();
       // dd($requestData);
        $masterModel = new MasterModel();

        try {
            $updateField['attribute_name']            = $requestData['edit_attribute_name'];
            //dd($updateField);
            $where['id']                    = $requestData['attribute_id'];
            $masterModel->updateData($updateField, 'report_attribute', $where);

        }catch(\Illuminate\Database\QueryException $ex){
            // $common     = new Common();
            // $common->error_logging($ex, 'Update', 'ReportSettingController.php');
            // return view('errors.oh!');
            dd($ex->getMessage());
            dd($ex->getLine());
        }
        return redirect('report_setting/edit?id='.$requestData['report_id'])->with('success','Field Updated successfully');
    }
}

src/resources/views/super_admin/Master/report_setting/reportSetting.blade.php
@extends('report::layouts.app')

@section('content')
<div class="container main-body">
    <div class="row">
        <div class="col-md-12">
            <?php if (Session::has('success')) : ?>
                <div class="alert alert-success">
                    <?php echo (Session::get('success')); ?>

                </div>
            <?php endif; ?>
            <a href={{ url('report_setting') }}>Back</a>
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Report Attribute</a>
                </li>
            </ul>
            <div class="tab-content pt-1" id="myTabContent">
                <!-- Form Fields -->
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <!-- Button trigger modal -->
                    <button type="button" class="btn-sm btn-sky-blue float-right" data-toggle="modal" data-target="#modalPopUpSetting"> Add Fields </button>
                    <span class="h6 font-weight500 text-orange"> Details of {{ $reportData->report_name }}</span>
                    <!-- Modal -->

                    <div class="table-responsive">
                        <table class="table table-border text-center mt-1">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody id="general_mst_data">
                                @foreach($reportAttributeData as $attribute)
                                    <tr>
                                        <td> {{ $attribute->id }}</td>
                                        <td> {{ $attribute->attribute_name }}</td>
                                        <td class="padding7px">
                                            <button type="button" class="btn btn-sm table-row-btn btnEditFields" id="editFormFields" data-toggle="modal" data-target="#formFieldEdit" data-attributeId="{{ $attribute->id }}">
                                                <span class="fa fa-edit"></span>
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-sm-10">
                            <div class="no_of_record">

                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div id="pagination">

                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>

<!-- Add Form Fields -->
<div class="modal fade" id="modalPopUpSetting" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Report Fields
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </h5>
            </div>
            <div class="modal-body">
                <form id="" role="form" method="post" action="{{ route('report_setting.store') }}">
                    @csrf
                    <input type="hidden" value="{{ $report_id }}" name="report_id">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="txtLabelName">Attribute Name</label>
                                <input type="text" name="attribute_name" class="form-control border-sky-blue" id="attribute_name" required>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <button type="reset" class="btn-sm btn-outline-sky-blue fa-pull-right">Reset</button>
                            <button type="submit" class="btn-sm btn-sky-blue fa-pull-right mr-1">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Edit Form Fields -->
<div class="modal fade" id="formFieldEdit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Report Attribute<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </h5>
            </div>
            <div class="modal-body">
                <form id="" role="form" method="post" action="update">
                    @csrf
                    <input type="hidden" value="{{ $report_id }}" name="report_id">
                    <input type="hidden" id="old_attribute_id" value="" name="attribute_id">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="txtLabelName">Attribute Name</label>
                                <input type="text" name="edit_attribute_name" class="form-control border-sky-blue" id="edit_attribute_name" required>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <button type="reset" class="btn-sm btn-outline-sky-blue fa-pull-right">Reset</button>
                            <button type="submit" class="btn-sm btn-sky-blue fa-pull-right mr-1">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>

    $('.btnEditFields').on('click', function() {
        var attribute_id = $(this).attr("data-attributeId");

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $.ajax({
            type: 'POST',
            url: APP_URL + '/editAttribute',
            data: {
                'attribute_id': attribute_id
            },
            success: function(ret_data) {

                var data = JSON.parse(ret_data);
                console.log(data);
                $('#old_attribute_id').val(attribute_id);
                $('#edit_attribute_name').val(data.attribute_name);
            }
        });
    });
</script>
@endsection